const mongoose = require( 'mongoose' );

const guildSchema = new mongoose.Schema({
    guildId: {
        type: mongoose.SchemaTypes.String,
        required: true,
        unique: true,
     },
    welcomechannel: {type: String },
    muterole: {type: String },
    byechannel: {type: String },
    counterm: {type: String },
    counterc: {type: String },
    counterb: {type: String },
    voicechannel: {type: String },
    logschannel: {type: String },
    prefix: {type: String },
    staffrole: {type: String },
    suggestionschannel: {type: String },
    ticketcategory: {type: String },
    welcomerole: {type: String },
    warnings: {type: Object},
    channelCreate: {type: Boolean},
    channelDelete: {type: Boolean},
    channelUpdate: {type: Boolean},
    channelPinsUpdate: {type: Boolean},
    emojiCreate: {type: Boolean},
    emojiDelete: {type: Boolean},
    emojiUpdate: {type: Boolean},
    guildBanAdd: {type: Boolean},
    guildBanRemove: {type: Boolean},
    guildMemberAdd: {type: Boolean},
    guildMemberRemove: {type: Boolean},
    guildMemberUpdate: {type: Boolean},
    guildScheduledEventCreate: {type: Boolean},
    guildScheduledEventDelete: {type: Boolean},
    guildScheduledEventUpdate: {type: Boolean},
    guildScheduledEventUserAdd: {type: Boolean},
    guildScheduledEventUserRemove: {type: Boolean},
    guildUpdate: {type: Boolean},
    inviteCreate: {type: Boolean},
    inviteDelete: {type: Boolean},
    messageDelete: {type: Boolean},
    messageDeleteBulk: {type: Boolean},
    messageReactionRemoveAll: {type: Boolean},
    messageUpdate: {type: Boolean},
    roleCreate: {type: Boolean},
    roleUpdate: {type: Boolean},
    stickerCreate: {type: Boolean},
    stickerDelete: {type: Boolean},
    stickerUpdate: {type: Boolean},
    threadCreate: {type: Boolean},
    threadDelete: {type: Boolean},
    threadMembersUpdate: {type: Boolean},
    threadMemberUpdate: {type: Boolean},
    threadUpdate: {type: Boolean},
    guild: {type: Boolean},
} );
const model = mongoose.model('guildModels', guildSchema);
module.exports = model;

